LEADER_NAMES = {
    1: "Captain Cutter",
    2: "Isabel",
    3: "Professor Anders",
    4: "Decimus",
    5: "Atriox",
    6: "Shipmaster",
    7: "Sergeant Forge",
    8: "Kinsano",
    9: "Commander Jerome",
    10: "The Arbiter",
    11: "Sergeant Johnson",
    12: "Colony",
    13: "Serina",
    14: "Yapyap THE DESTROYER",
    15: "Pavium",
    16: "Voridus",
}

MAP_NAMES = {
    "rostermode\\design\\RM_EvenFlow_Desert\\RM_EvenFlow_Desert": "SIROCCO",
    "rostermode\\design\\RM_EvenFlowArt\\RM_EvenFlowArt": "The Proving Grounds",
    "rostermode\\design\\RM_EvenFlowNight\\RM_EvenFlowNight": "NOCTURNE",
    "skirmish\\design\\Ep02_M03\\Ep02_M03": "FISSURES",
    "skirmish\\design\\FF_StopTheSignal\\FF_StopTheSignal": "HIGH BASTION",
    "skirmish\\design\\fort_jordan\\fort_jordan": "FORT JORDAN",
    "skirmish\\design\\MC_EnforcerValley\\MC_EnforcerValley": "MIRAGE",
    "skirmish\\design\\MP_Boneyard\\MP_Boneyard": "HIGHWAY",
    "skirmish\\design\\MP_Bridges\\MP_Bridges": "FRONTIER",
    "skirmish\\design\\MP_Caldera\\MP_Caldera": "ASHES",
    "skirmish\\design\\MP_Eagle\\MP_Eagle": "BADLANDS",
    "skirmish\\design\\MP_Fracture\\MP_Fracture": "RIFT",
    "skirmish\\design\\MP_Razorblade\\MP_Razorblade": "BEDROCK",
    "skirmish\\design\\MP_Ricochet\\MP_Ricochet": "SENTRY",
    "skirmish\\design\\MP_Veteran\\MP_Veteran": "VAULT",
}
